import { stringify } from 'yaml';
import type { Config, Module } from '../config/schema.js';
import type { ComposerState } from './composer-state.js';

/**
 * Generate configuration from Composer state
 */
export function generateConfig(state: ComposerState): Config {
  const modules: Module[] = [];

  // 1. Add all enabled modules
  for (const mod of state.modules) {
    if (!mod.enabled) continue;

    if (mod.type === 'docker') {
      modules.push({
        name: mod.name,
        type: 'docker',
        composeFile: mod.path,
        enabled: true,
        dependsOn: [],
        // services? profiles? - To be enhanced in V2
        // For now, simple compose file reference
      });
    } else {
      // workspace or worker
      const moduleConfig: Module = {
        name: mod.name,
        type: 'workspace', // schema only supports 'workspace' | 'docker' | 'custom'
        path: mod.path,
        run: mod.commands,
        enabled: true,
        dependsOn: mod.dependsOn,
        packageManager: 'auto',
      };

      modules.push(moduleConfig);
    }
  }

  const customScripts: Record<string, string> = {};
  for (const [name, enabled] of Object.entries(state.customScripts)) {
    if (enabled) {
      customScripts[name] = state.rootScripts[name] ?? '';
    }
  }

  const config: Config = {
    version: '1',
    global: {
      logsDir: './tmp',
      autoAllocatePorts: true, // Defaulting to true for now
      prerequisites: {
        node: state.nodeVersion,
        docker: state.requireDocker,
        dockerCompose: state.requireDockerCompose,
      },
    },
    modules,
  };

  if (Object.keys(customScripts).length > 0) {
    config.customScripts = customScripts;
  }

  return config;
}

/**
 * Generate YAML string from configuration
 */
export function configToYaml(config: Config): string {
  // Use yaml library to stringify
  // We want a clean output, maybe some comments?
  // yaml lib doesn't support comments easily during stringify.
  // We can add a header manually.

  const yaml = stringify(config, {
    indent: 2,
    lineWidth: 0, // Disable line wrapping
    aliasDuplicateObjects: false,
  });

  return `# Canto Development Configuration
# Generated by Canto Composer
# https://github.com/Excelsi-Innovations/canto

${yaml}`;
}
